# Generated by Django 5.2 on 2025-07-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsingModels', '0004_drummers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
