# Generated by Django 5.2 on 2025-07-13 12:38

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsingModels', '0007_siteusers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siteusers',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
