# Generated by Django 5.2 on 2025-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsingModels', '0010_businessorders_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
    ]
