# Generated by Django 5.2 on 2025-07-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsingModels', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drummers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=8)),
            ],
            options={
                'db_table': 'Drummers',
            },
        ),
    ]
