# Generated by Django 5.2 on 2025-07-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsingModels', '0009_orders_businessorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
